#!/bin/zsh
rm -rf lib > /dev/null
mkdir -p lib/C
chdir lib/C
cp ~/lbl-libc/C/*.c .
cp ~/lbl-libc/C/*.h .
cp ~/lbl-libc/C/*.h ../../include
gcc -c *.c -g3 -fPIC -Werror -Wall -Wextra -W
ar rc libmy.a *.o
rm *.o
my_put BOLDBLUE "Your own C Library "
my_put BOLDGREEN "<libmy.a> "
my_put BOLDBLUE "has been succesfully compilated and added to your current directory"
echo
