#!/bin/zsh
mkdir include
mkdir lib
mkdir src
cp ~/lbl-libc/Makefile .
touch .gitignore
touch sc
echo "src/*.o" >> .gitignore
echo "sc" >> .gitignore
echo "make re" >> sc
echo "make fclean" >> sc
echo "mr_clean" >> sc
chmod 777 sc
my_lib
